---
- hosts: remote
  sudo: yes
  tasks:
    - name: install apache2
      yum: name=httpd state=latest
    - name: Copy the source file to apache server
      copy: src=/etc/ansible/index.html dest=/var/www/html
    - name: start and enable httpd service
      service: name=httpd state=restarted enabled=yes

